### ISSUE TITLE
Relations with multiple but identical senses

### ISSUE THREAD

**Issue by jonathon-read** [attapol/conll16st#6]
Hello, and thank you for your work in looking after the data! We've observed a few instances where relations have two senses listed, but the two senses are identical. I just thought I'd raise them with you in case there is any impact on the evaluation data or scripts.

| Subset | DocID | ID | Sense[0] | Sense[1] |
| :-: | :-: | :-: | :-: | :-: |
| en.train | wsj_0207 | 3214 | Expansion.Alternative | Expansion.Alternative |
| en.train | wsj_0266 | 3857 | Expansion.Alternative | Expansion.Alternative |
| en.train | wsj_0518 | 7995 | Contingency.Cause.Reason | Contingency.Cause.Reason |
| en.train | wsj_0524 | 8086 | Contingency.Cause.Reason | Contingency.Cause.Reason |
| en.train | wsj_0525 | 8121 | Contingency.Cause.Reason | Contingency.Cause.Reason |
| en.train | wsj_0530 | 8240 | Contingency.Cause.Reason | Contingency.Cause.Reason |
| en.train | wsj_0552 | 8410 | Contingency.Cause.Reason | Contingency.Cause.Reason |
| en.train | wsj_0553 | 8447 | Contingency.Cause.Reason | Contingency.Cause.Reason |
| en.train | wsj_0569 | 8886 | Expansion.Alternative | Expansion.Alternative |

**Comment by attapol** [comment]
That is a good catch. It does not have an effect on evaluation though. But we will definitely fix this before the next release of the data.
