### ISSUE TITLE
Validator.py 

### ISSUE THREAD

**Issue by jndevanshu** [attapol/conll16st#9]
On running the validator.py script, I get this error:
**Relation 599 Invalid sense of Contingency.Cause**
Why is the sense "Contingency.Cause" invalid?

**Comment by attapol** [comment]
Contingency.Cause is an incomplete label. Therefore, invalid.
Contingency.Cause.Reason or Contingency.Cause.Result are valid labels.

This is a good question. but please post questions on google group. So most participants will benefit from it too.
